spring:
  application:
    name: Library
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: library
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: on