drop table if exists Book;

create table Book (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    publisher varchar(255) not null,
    student_name varchar(255),
    issue_date date,
    return_date date,
    thumbnail_url varchar(255)
);